"""Orchestrator: download all CIKM datasets.

Default 4 datasets (all proven to work):
  - WebQSP    (multi-hop QA, via HF datasets)
  - CWQ       (compositional multi-hop QA, via HF datasets)
  - ICEWS18   (temporal KG, via RE-Net raw files)
  - OrgAccess (dynamic policy, synthetic — generated by us)

Optional (off by default, use --with-dbp15k to attempt):
  - DBP15K    (cross-lingual entity alignment). Public mirrors are unreliable;
              if download fails, follow manual instructions in README.

The orchestrator continues past individual failures and never raises.

Usage:
    python -m scripts.download.download_all --root /content/drive/MyDrive/quest_kg/data
    python -m scripts.download.download_all --root <ROOT> --with-dbp15k
"""
from __future__ import annotations

import argparse
import importlib
import sys
import traceback
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))


DEFAULT_DATASETS = [
    ("download_webqsp",  {}),
    ("download_cwq",     {}),
    ("download_icews18", {}),
]


def main(root: str, with_dbp15k: bool = False) -> None:
    ok, failed = [], []

    datasets = list(DEFAULT_DATASETS)
    if with_dbp15k:
        datasets.insert(0, ("download_dbp15k", {}))

    for mod_name, kw in datasets:
        print("=" * 60)
        print(f"[orchestrator] running {mod_name}")
        try:
            mod = importlib.import_module(f"scripts.download.{mod_name}")
            mod.main(root=root, **kw)
            ok.append(mod_name)
        except Exception as e:
            print(f"[orchestrator] {mod_name} failed: {e}")
            traceback.print_exc()
            failed.append(mod_name)

    # OrgAccess (synthetic, always works)
    print("=" * 60)
    print("[orchestrator] generating orgaccess (synthetic)")
    try:
        mod = importlib.import_module("scripts.download.generate_orgaccess")
        mod.main(root=root, n_users=500, n_resources=200, n_policies=50,
                 n_contexts=8, n_queries=5000, T_horizon=200, seed=0)
        ok.append("orgaccess")
    except Exception as e:
        print(f"[orchestrator] orgaccess failed: {e}")
        traceback.print_exc()
        failed.append("orgaccess")

    print("=" * 60)
    print("SUMMARY")
    print(f"  OK    : {ok}")
    print(f"  FAILED: {failed}")
    print("=" * 60)
    if not with_dbp15k:
        print("\nNote: DBP15K (entity alignment) is off by default since public mirrors are unreliable.")
        print("      The 4 datasets above cover the main paper story (QA + temporal + policy).")
        print("      To attempt DBP15K download: pass --with-dbp15k.")
    if failed:
        print(f"\nFailures: {failed}. Run the individual scripts directly for verbose errors.")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", required=True)
    ap.add_argument("--with-dbp15k", action="store_true",
                    help="Attempt DBP15K entity alignment download (mirrors unreliable; off by default)")
    args = ap.parse_args()
    main(args.root, with_dbp15k=args.with_dbp15k)
